language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - composer self-update
  - cd ..
  - git clone --depth 1 --branch 8.0.x http://git.drupal.org/project/drupal.git
  - mv drupal_flysystem drupal/modules/flysystem
  - cd drupal

script:
  - travis_retry composer require league/flysystem ^1.0.3 --prefer-source
  - travis_retry composer require league/flysystem-cached-adapter ~1.0 --prefer-source
  - travis_retry composer require league/flysystem-memory ~1.0 --prefer-source
  - travis_retry composer require league/flysystem-replicate-adapter ~1.0 --prefer-source
  - travis_retry composer require twistor/flysystem-stream-wrapper ^1.0.5 --prefer-source

  - cd modules/flysystem
  - ../../vendor/bin/phpunit

notifications:
  email: false
